databases:
  - name: recognition
    databaseName: recognition
    user: recognition

services:
  - type: web
    name: recognition
    plan: individual
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recognition
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false